### PR TITLE
Fix Discord link

### PR DESCRIPTION
**Pull request by ghost**
Original Discord link doesn't work because it redirects to the chat channel. Fixed it using the User ID link.

### CODE REVIEW

**Comment by koumaza** [comment]
Oh, Thank you!!😊
I'd like `canary.discordapp.com` if you like~

**Comment by ghost** [comment]
Oh ok I fixed it.

**Review by koumaza — APPROVED** [review]

**Comment by koumaza** [comment]
Thank you!!!

**Comment by koumaza** [comment]
BTW, I lost access to my account🙃🙃🙃🙃
image

**Comment by ghost** [comment]
Oh.....😭

**Pull request merged**
